### ISSUE TITLE
Not using nodejs, instead the html and js files in an mvc application

### ISSUE THREAD

**Issue by valnav** [billba/agent#2]
I am able to run the agent ui successfully. but, for every new message from the user it is starting up a new agent ui chat frame. What am I doing wrong?

**Comment by billba** [comment]
I'm sorry, this is old sample code and I'm not maintaining it.

**Comment by jrmcdona** [comment]
@valnav It does that for me too.   Did you ever figure it out?
I am trying to do this sample https://github.com/tompaana/intermediator-bot-sample
