### ISSUE TITLE
Error while building bot

### ISSUE THREAD

**Issue by vinayjayaram** [billba/agent#3]
node_modules/@types/whatwg-fetch/index.d.ts(11,13): error TS2300: Duplicate identifier 'fetch'.
node_modules/@types/whatwg-fetch/index.d.ts(13,14): error TS2300: Duplicate identifier 'HeadersInit'.
node_modules/@types/whatwg-fetch/index.d.ts(14,15): error TS2300: Duplicate identifier 'Headers'.
node_modules/@types/whatwg-fetch/index.d.ts(31,14): error TS2300: Duplicate identifier 'BodyInit'.
node_modules/@types/whatwg-fetch/index.d.ts(33,5): error TS2687: All declarations of 'bodyUsed' must have identical modifiers.
node_modules/@types/whatwg-fetch/index.d.ts(41,14): error TS2300: Duplicate identifier 'RequestInfo'.
node_modules/@types/whatwg-fetch/index.d.ts(42,15): error TS2300: Duplicate identifier 'Request'.
node_modules/@types/whatwg-fetch/index.d.ts(61,11): error TS2300: Duplicate identifier 'Request'.
node_modules/@types/whatwg-fetch/index.d.ts(65,5): error TS2717: Subsequent property declarations must have the same type.  Property 'body' must be of type 'string | Int8Array | Uint8Array | Uint8ClampedArray | Int16Array | Uint16Array | Int32Array | Uin...', but here has type 'any'.
node_modules/@types/whatwg-fetch/index.d.ts(76,6): error TS2300: Duplicate identifier 'RequestType'.
node_modules/@types/whatwg-fetch/index.d.ts(77,6): error TS2300: Duplicate identifier 'RequestDestination'.
node_modules/@types/whatwg-fetch/index.d.ts(78,6): error TS2300: Duplicate identifier 'RequestMode'.
node_modules/@types/whatwg-fetch/index.d.ts(79,6): error TS2300: Duplicate identifier 'RequestCredentials'.
node_modules/@types/whatwg-fetch/index.d.ts(80,6): error TS2300: Duplicate identifier 'RequestCache'.
node_modules/@types/whatwg-fetch/index.d.ts(81,6): error TS2300: Duplicate identifier 'RequestRedirect'.
node_modules/@types/whatwg-fetch/index.d.ts(82,6): error TS2300: Duplicate identifier 'ReferrerPolicy'.
node_modules/@types/whatwg-fetch/index.d.ts(84,15): error TS2300: Duplicate identifier 'Response'.
node_modules/@types/whatwg-fetch/index.d.ts(102,11): error TS2300: Duplicate identifier 'Response'.
node_modules/@types/whatwg-fetch/index.d.ts(109,6): error TS2300: Duplicate identifier 'ResponseType'.
node_modules/typescript/lib/lib.dom.d.ts(2109,14): error TS2687: All declarations of 'bodyUsed' must have identical modifiers.
node_modules/typescript/lib/lib.dom.d.ts(8120,11): error TS2300: Duplicate identifier 'Headers'.
node_modules/typescript/lib/lib.dom.d.ts(8129,13): error TS2300: Duplicate identifier 'Headers'.
node_modules/typescript/lib/lib.dom.d.ts(10577,11): error TS2300: Duplicate identifier 'Request'.
node_modules/typescript/lib/lib.dom.d.ts(10595,13): error TS2300: Duplicate identifier 'Request'.
node_modules/typescript/lib/lib.dom.d.ts(10600,11): error TS2300: Duplicate identifier 'Response'.
node_modules/typescript/lib/lib.dom.d.ts(10612,13): error TS2300: Duplicate identifier 'Response'.
node_modules/typescript/lib/lib.dom.d.ts(15933,18): error TS2300: Duplicate identifier 'fetch'.
node_modules/typescript/lib/lib.dom.d.ts(15944,6): error TS2300: Duplicate identifier 'HeadersInit'.
node_modules/typescript/lib/lib.dom.d.ts(15950,6): error TS2300: Duplicate identifier 'BodyInit'.
node_modules/typescript/lib/lib.dom.d.ts(15977,6): error TS2300: Duplicate identifier 'RequestInfo'.
node_modules/typescript/lib/lib.dom.d.ts(16051,6): error TS2300: Duplicate identifier 'ReferrerPolicy'.
node_modules/typescript/lib/lib.dom.d.ts(16052,6): error TS2300: Duplicate identifier 'RequestCache'.
node_modules/typescript/lib/lib.dom.d.ts(16053,6): error TS2300: Duplicate identifier 'RequestCredentials'.
node_modules/typescript/lib/lib.dom.d.ts(16054,6): error TS2300: Duplicate identifier 'RequestDestination'.
node_modules/typescript/lib/lib.dom.d.ts(16055,6): error TS2300: Duplicate identifier 'RequestMode'.
node_modules/typescript/lib/lib.dom.d.ts(16056,6): error TS2300: Duplicate identifier 'RequestRedirect'.
node_modules/typescript/lib/lib.dom.d.ts(16057,6): error TS2300: Duplicate identifier 'RequestType'.
node_modules/typescript/lib/lib.dom.d.ts(16058,6): error TS2300: Duplicate identifier 'ResponseType'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! agent@0.1.0 build: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the agent@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/igate/.npm/_logs/2018-04-13T10_25_52_717Z-debug.log

**Comment by adamdharris** [comment]
@vinayjayaram did you resolve your error?

**Comment by vinayjayaram** [comment]
@adamdharris  Not yet

**Comment by piriej** [comment]
I was experiencing the same issue. For those who experience this,

I believe the issue is to do with @types/whatwg-fetch, being in your node modules folder. 

If you are running a recent version of typescript (I am running 2.8.3), then @types/whatwg-fetch is now built into typescript. 

You should now be able to remove it: npm uninstall @types/whatwg-fetch, and build subsequently works.

**Comment by billba** [comment]
Sorry I'm not supporting this repo.
