### ISSUE TITLE
https://github.com/billba/agent

### ISSUE THREAD

**Issue by tomeelog** [billba/agent#4]
I got this error  when I run build
node_modules/@types/whatwg-streams/index.d.ts(103,32): error TS1005: ',' expected. node_modules/@types/whatwg-streams/index.d.ts(110,32): error TS1005: ',' expected. node_modules/@types/whatwg-streams/index.d.ts(119,45): error TS1005: ',' expected. node_modules/@types/whatwg-streams/index.d.ts(132,49): error TS1005: ',' expected. node_modules/@types/whatwg-streams/index.d.ts(136,43): error TS1005: ',' expected.
-- | --

**Comment by billba** [comment]
This is a very old and unsupported project, sorry.
